Models/Inmueble.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;


namespace WebApplicationPrueba.Models
{
    public enum enEstado
    {
        Disponible = 1,
        No_disponible = 2,
        En_Refaccion = 3,
    }
    public class Inmueble
    {
        [Display(Name = "Código")]
        public int Id { get; set; }
        [Required]
        public string Direccion { get; set; }
        [Required]
        public int Ambientes { get; set; }
        [Required]
        public string Tipo { get; set; }
        [Required]
        public string Uso { get; set; }
        [Required]
        public int Superficie { get; set; }
        public decimal Latitud { get; set; }
        public decimal Longitud { get; set; }
        [Required]
        public decimal Precio { get; set; }
        [Required]
        public int Estado { get; set; }
        //[Display(Name = "Dueño")]
        public int PropietarioId { get; set; }
        //[ForeignKey("PropietarioId")]
        public Propietario Duenio { get; set; }

        public string Foto { get; set; }


        [Display(Name = "Estado")]
        public string EstadoNombre => Estado > 0 ? ((enEstado)Estado).ToString().Replace('_', ' ') : "";

        public static IDictionary<int, string> ObtenerRoles()
        {
            SortedDictionary<int, string> estados = new SortedDictionary<int, string>();
            Type tipoEnumEstado = typeof(enEstado);
            foreach (var valor in Enum.GetValues(tipoEnumEstado))
            {
                estados.Add((int)valor, Enum.GetName(tipoEnumEstado, valor).Replace('_',' '));
            }
            return estados;
        }

    }
}

Controllers/InmuebleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using WebApplicationPrueba.Models;

namespace WebApplicationPrueba.Controllers
{
    public class InmuebleController : Controller
    {
        private readonly IConfiguration configuration;
        private readonly IRepositorioInmueble repositorio;
        private readonly IRepositorioPropietario repoPropietario;


        public InmuebleController(IConfiguration configuration, IRepositorioInmueble repositorio, IRepositorioPropietario repoPropietario)
        {
            this.configuration = configuration;
            this.repositorio = repositorio;
            this.repoPropietario = repoPropietario;
        }

        // GET: Inmueble
        [Authorize]
        public ActionResult Index()
        {
            var lista = repositorio.ObtenerTodos();
            if (TempData.ContainsKey("Id"))
                ViewBag.Id = TempData["Id"];
            if (TempData.ContainsKey("Mensaje"))
                ViewBag.Mensaje = TempData["Mensaje"];
            return View(lista);
        }

        [Authorize]
        public ActionResult IndexPorPropietario(int id)
        {
            var lista = repositorio.BuscarPorPropietario(id);
            if (TempData.ContainsKey("Id"))
                ViewBag.Id = TempData["Id"];
            if (TempData.ContainsKey("Mensaje"))
                ViewBag.Mensaje = TempData["Mensaje"];
            return View("Index", lista);
        }

        [Authorize]
        [Route("[controller]/BuscarInmueblePorFecha/{desde}/{hasta}", Name = "BuscarInmueblePorFecha")]
        public IActionResult BuscarInmueblePorFecha(DateTime desde, DateTime hasta)
        {
            try
            {
                var res = repositorio.ObtenerPorFecha(desde, hasta);
                return Json(new { Datos = res });
            }
            catch (Exception ex)
            {
                return Json(new { Error = ex.Message });
            }
        }

        [Authorize]
        [Route("[controller]/BuscarDisponibles/{estado}", Name = "BuscarDisponibles")]
        public IActionResult BuscarDisponibles(Boolean estado)
        {
            try
            {
                var res = repositorio.ObtenerTodos(estado);
                return Json(new { Datos = res });
            }
            catch (Exception ex)
            {
                return Json(new { Error = ex.Message });
            }
        }

        // GET: Inmueble/Details/5
        [Authorize]
        public ActionResult Details(int id)
        {
            var entidad = repositorio.ObtenerPorId(id);
            return View(entidad);
        }

        // GET: Inmueble/Create
        [Authorize]
        public ActionResult Create()
        {
            ViewBag.Propietarios = repoPropietario.ObtenerTodos();
            ViewBag.Estado = Inmueble.ObtenerRoles();
            return View();
        }

        // POST: Inmueble/Create
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Inmueble entidad)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    repositorio.Alta(entidad);
                    TempData["Id"] = entidad.Id;
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    ViewBag.Propietarios = repoPropietario.ObtenerTodos();
                    return View(entidad);
                }
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                ViewBag.StackTrate = ex.StackTrace;
                return View(entidad);
            }
        }

        // GET: Inmueble/Edit/5
        [Authorize]
        public ActionResult Edit(int id)
        {
            var entidad = repositorio.ObtenerPorId(id);
            ViewBag.Propietarios = repoPropietario.ObtenerTodos();
            ViewBag.Estado = Inmueble.ObtenerRoles();
            if (TempData.ContainsKey("Mensaje"))
                ViewBag.Mensaje = TempData["Mensaje"];
            if (TempData.ContainsKey("Error"))
                ViewBag.Error = TempData["Error"];
            return View(entidad);
        }

        // POST: Inmueble/Edit/5
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Inmueble entidad)
        {
            try
            {
                entidad.Id = id;
                repositorio.Modificacion(entidad);
                TempData["Mensaje"] = "Datos guardados correctamente";
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.Propietarios = repoPropietario.ObtenerTodos();
                ViewBag.Error = ex.Message;
                ViewBag.StackTrate = ex.StackTrace;
                return View(entidad);
            }
        }

        // GET: Inmueble/Eliminar/5
        [Authorize(Policy = "Administrador")]
        public ActionResult Eliminar(int id)
        {

            try
            {
                repositorio.Baja(id);
                TempData["Mensaje"] = "Eliminación realizada correctamente";
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                ViewBag.StackTrate = ex.StackTrace;
                return RedirectToAction(nameof(Index));
            }
        }

        // POST: Inmueble/Eliminar/5
        [Authorize(Policy = "Administrador")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Eliminar(int id, Inmueble entidad)
        {
            try
            {
                repositorio.Baja(id);
                TempData["Mensaje"] = "Eliminación realizada correctamente";
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                ViewBag.StackTrate = ex.StackTrace;
                return View(entidad);
            }
        }
    }
}

Views/Inmueble/Create.cshtml
@model WebApplicationPrueba.Models.Inmueble

@{
    ViewData["Title"] = "Crear";
}

<h1>Crear</h1>

<h4>Inmueble</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <label asp-for="Direccion" class="control-label"></label>
                <input asp-for="Direccion" class="form-control" />
                <span asp-validation-for="Direccion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Ambientes" class="control-label"></label>
                <input asp-for="Ambientes" class="form-control" />
                <span asp-validation-for="Ambientes" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Tipo" class="control-label"></label>
                <input asp-for="Tipo" class="form-control" />
                <span asp-validation-for="Tipo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Uso" class="control-label"></label>
                <input asp-for="Uso" class="form-control" />
                <span asp-validation-for="Uso" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Superficie" class="control-label"></label>
                <input asp-for="Superficie" class="form-control" />
                <span asp-validation-for="Superficie" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Latitud" class="control-label"></label>
                <input asp-for="Latitud" class="form-control" />
                <span asp-validation-for="Latitud" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Longitud" class="control-label"></label>
                <input asp-for="Longitud" class="form-control" />
                <span asp-validation-for="Longitud" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Precio" class="control-label"></label>
                <input asp-for="Precio" class="form-control" />
                <span asp-validation-for="Precio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Estado" class="control-label"></label>
                <input asp-for="Estado" class="form-control" />
                <span asp-validation-for="Estado" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label class="control-label">Propietario</label>
                <select class="form-control" name="PropietarioId">
                    @foreach (var item in (IList<Propietario>)ViewBag.Propietarios)
                    {
                        <option value="@item.Id">@(item.Nombre + " " + item.Apellido + " :"+item.Dni)</option>
                    }
                </select>
                <span asp-validation-for="PropietarioId" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label class="control-label">Estado</label>
                <select class="form-control" name="Estado">
                    @foreach (var kvp in (IDictionary<int, string>)ViewBag.Estado)
                    {
                        <option value="@kvp.Key">@kvp.Value</option>
                    }
                </select>
                <span asp-validation-for="Estado" class="text-danger"></span>
            </div>


            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-outline-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a class="btn btn-outline-danger" asp-action="Index">Volver a la lista</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Inmueble/Details.cshtml
@model WebApplicationPrueba.Models.Inmueble

@{
    ViewData["Title"] = "Detalles";
}

<h1>Detalles</h1>

<div>
    <h4>Inmueble</h4>
    <hr />
    <dl class="row">
      
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Direccion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Direccion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Ambientes)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Ambientes)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Tipo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Tipo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Uso)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Uso)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Superficie)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Superficie)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Latitud)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Latitud)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Longitud)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Longitud)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Precio)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Precio)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Duenio)
        </dt>
        <dd class="col-sm-10">
            <a class="btn btn-outline-secondary" asp-controller="Propietario" asp-action="Edit" asp-route-id="@Model.Duenio.Id" title="Editar"> @(Model.Duenio.Nombre + " " + Model.Duenio.Apellido)</a>

        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EstadoNombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EstadoNombre)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Editar", "Edit", new { id = Model.Id }, new { @class = "btn btn-outline-warning" })

    <a class="btn btn-outline-danger" asp-action="Index">Volver a la lista</a>
</div>

Views/Inmueble/Edit.cshtml
@model WebApplicationPrueba.Models.Inmueble

@{
    ViewData["Title"] = "Editar";
}

<h1>Editar</h1>

<h4>Inmueble</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <label asp-for="Direccion" class="control-label"></label>
                <input asp-for="Direccion" class="form-control" />
                <span asp-validation-for="Direccion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Ambientes" class="control-label"></label>
                <input asp-for="Ambientes" class="form-control" />
                <span asp-validation-for="Ambientes" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Tipo" class="control-label"></label>
                <input asp-for="Tipo" class="form-control" />
                <span asp-validation-for="Tipo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Uso" class="control-label"></label>
                <input asp-for="Uso" class="form-control" />
                <span asp-validation-for="Uso" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Superficie" class="control-label"></label>
                <input asp-for="Superficie" class="form-control" />
                <span asp-validation-for="Superficie" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Latitud" class="control-label"></label>
                <input asp-for="Latitud" class="form-control" />
                <span asp-validation-for="Latitud" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Longitud" class="control-label"></label>
                <input asp-for="Longitud" class="form-control" />
                <span asp-validation-for="Longitud" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Precio" class="control-label"></label>
                <input asp-for="Precio" class="form-control" />
                <span asp-validation-for="Precio" class="text-danger"></span>
            </div>
            @if (User.IsInRole("Administrador") || User.IsInRole("SuperAdministrador"))
            {
                <div class="form-group">
                    <label class="control-label">Estado</label>
                    <select class="form-control" name="Estado">
                        @foreach (var kvp in (IDictionary<int, string>)ViewBag.Estado)
                        {
                            @:<option @(kvp.Key == Model.Estado ? "selected" : "") value="@kvp.Key">@kvp.Value</option>
                        }
                    </select>
                    <span asp-validation-for="Estado" class="text-danger"></span>
                </div>
            }
            <div class="form-group">
                <label class="control-label">Propietario</label>
                <select class="form-control" name="PropietarioId">
                    @foreach (var item in (IList<Propietario>)ViewBag.Propietarios)
                    {
                        @:<option @(item.Id == Model.PropietarioId ? "selected" : "") value="@item.Id">@(item.Nombre + " " + item.Apellido +" "+item.Dni)</option>
                    }
                </select>
                <span asp-validation-for="PropietarioId" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-outline-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a class="btn btn-outline-danger" asp-action="Index">Volver a la lista</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Inmueble/Index.cshtml
@model IEnumerable<WebApplicationPrueba.Models.Inmueble>

@{
    ViewData["Title"] = "Inmuebles";
}


<div class="row">
    <div class="col-1">

    </div>
    <div class="col-4 mt-2 pt-2">
        <h1>Inmuebles</h1>
        <div class="row-4">
            <div class="input-group mb-3 mt-3">
                <div class="input-group-prepend">
                    <div class="input-group-text">
                        <input id="check-box-div" type="checkbox" aria-label="Checkbox for following text input">
                    </div>
                </div>
                <span>Disponibles</span>
            </div>
        </div>

        <div class="row-4">
            <p>
                <a class="btn btn-outline-success" asp-action="Create">Crear Inmueble</a>
            </p>
        </div>


    </div>
    <div class="col-1">

    </div>
    <div class="col-4 mt-2 pt-2">
        <div class="row-4">

        </div>
        <div class="row-4">
            <form id="form-buscarr">
                <div class="form-group">

                    <label for="desde" class="control-label"></label>
                    <input type="date" name="desde" class="form-control" placeholder="Buscar Desde" id="desdee" />
                    <span>
                        <label for="hasta" class="control-label"></label>
                        <input type="date" name="hasta" class="form-control" placeholder="Buscar Hasta" id="hastaa" />
                    </span>
                    <div class="form-group mt-2 justify-content-xl-center">
                        <input type="submit" value="Buscar" class="btn btn-outline-primary" />
                    </div>
                </div>
            </form>
        </div>

    </div>
</div>


<table class="table table-striped table-bordered table-hover">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Direccion)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Ambientes)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Tipo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Uso)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Superficie)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Latitud)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Longitud)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Precio)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PropietarioId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EstadoNombre)
            </th>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody id="resultado">
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Direccion)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Ambientes)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Tipo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Uso)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Superficie)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Latitud)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Longitud)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Precio)
                </td>

                <td>
                    @(item.Duenio.Nombre + " "+ item.Duenio.Apellido)
                </td>

                <td style="background-color:@( item.Estado==1 ? "#A4F762" : "#E15F43" )">
                    @Html.DisplayFor(modelItem => item.EstadoNombre)
                </td>
                <td>
                    <span>@Html.ActionLink("", "Edit", new { id = item.Id }, new { @class = "btn btn-outline-warning fa fa-pencil" })</span>
                </td>
                <td>
                    <span>@Html.ActionLink("", "Details", new { id = item.Id }, new { @class = "btn btn-outline-primary fa  fa-info" })</span>
                </td>
                <td>
                    <span>@Html.ActionLink("", "Eliminar", new { id = item.Id }, new { @class = "btn btn-outline-danger fa fa-trash" })</span>
                </td>
                <td>
                    <a class="btn btn-outline-secondary" asp-controller="Contrato" asp-action="IndexPorInmueble" asp-route-id="@item.Id" title="Contratos del Inmueble"><i class="fa fa-gavel"></i></a>
                </td>
            </tr>
        }
    </tbody>
</table>

<!--Scripts-->
<script id="t_tabla" type="x-tmpl-mustache">
    {{#datos}}
    <tr>
        <td>
            {{direccion}}
        </td>
        <td>
            {{ambientes}}
        </td>
        <td>
            {{tipo}}
        </td>
        <td>
            {{uso}}
        </td>
        <td>
            {{superficie}}
        </td>
        <td>
            {{latitud}}
        </td>
        <td>
            {{longitud}}
        </td>
        <td>
            {{precio}}
        </td>
        <td>
            {{duenio.nombre}} {{duenio.apellido}}
        </td>
        <td >
            {{estadoNombre}}
        </td>
        <td>
            <a href="Inmueble/Edit/{{id}}" class="btn btn-outline-warning fa fa-pencil"></a>
        </td>
        <td>
            <a href="Inmueble/Details/{{id}}" class="btn btn-outline-primary fa  fa-info"></a>
        </td>
        <td>
            <a href="Inmueble/Eliminar/{{id}}" class="btn btn-outline-danger fa fa-trash"></a>
        </td>
        <td>
            <a href="Contrato/IndexPorInmueble/{{id}}" class="btn btn-outline-secondary fa fa-gavel"></a>
        </td>
    </tr>

    {{/datos}}
</script>




@section Scripts{
    <script>
        document.querySelector("#check-box-div").addEventListener("change", (e) => {

            e.preventDefault();

            if ($("#check-box-div").is(':checked')) {
                var estado = true;
            } else {
                var estado = false;
            }
               $.get(`@Url.Action("BuscarDisponibles", "Inmueble")/${estado}`).done((res) => {
                console.log(res);
                var template = document.getElementById('t_tabla').innerHTML;
                var rendered = Mustache.render(template, res);
                document.getElementById('resultado').innerHTML = rendered;
            });
            return false;
        });


         document.querySelector("#form-buscarr").addEventListener("submit", (e) => {

            e.preventDefault();
            var desde = $('#desdee').val();
            var hasta = $('#hastaa').val();
            $.get(`@Url.Action("BuscarInmueblePorFecha", "Inmueble")/${desde}/${hasta}`).done((res) => {
                console.log(res);
                var template = document.getElementById('t_tabla').innerHTML;
                var rendered = Mustache.render(template, res);
                document.getElementById('resultado').innerHTML = rendered;
            });
            return false;
        });

    </script>
}