Models/Contrato.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace WebApplicationPrueba.Models
{
    public class Contrato
    {
        [Display(Name = "Código")]
        public int Id { get; set; }
        
        [Display(Name = "Fecha Emision")]
        [Required, DataType(DataType.Date)]
        public DateTime FechaDesde { get; set; }

        [Required, DataType(DataType.Date)]
        [Display(Name = "Fecha Vencimiento")]
        public DateTime FechaHasta { get; set; }

        [Required]
        [Display(Name = "Precio")]
        public decimal PrecioMensual { get; set; }


        [Display(Name = "Inquilino")]
        public int InquilinoId { get; set; }
        [ForeignKey("InquilinoId")]
        public Inquilino Inquilino { get; set; }


        [Display(Name = "Inmueble")]
        public int InmuebleId { get; set; }
        [ForeignKey("InmuebleId")]
        public Inmueble Inmueble { get; set; }
    }
}

Controllers/ContratoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using WebApplicationPrueba.Models;

namespace WebApplicationPrueba.Controllers
{
    public class ContratoController : Controller
    {
        private readonly IRepositorioContrato repositorio;
        private readonly IRepositorioInmueble repositorioInmueble;
        private readonly IRepositorioPropietario repoPropietario;
        private readonly IRepositorioInquilino repoInquilinos;

        public ContratoController(IConfiguration configuration, IRepositorioContrato repositorio, IRepositorioInmueble repositorioInmueble, IRepositorioPropietario repoPropietario, IRepositorioInquilino repoInquilinos)
        {
            this.repositorio = repositorio;
            this.repoPropietario = repoPropietario;
            this.repositorioInmueble = repositorioInmueble;
            this.repoInquilinos = repoInquilinos;
        }



        // GET: ContratoController
        [Authorize]
        public ActionResult Index()
        {
            var lista = repositorio.ObtenerTodos();
            if (TempData.ContainsKey("Id"))
                ViewBag.Id = TempData["Id"];
            if (TempData.ContainsKey("Mensaje"))
                ViewBag.Mensaje = TempData["Mensaje"];
            return View(lista);
        }

        [Authorize]
        public ActionResult IndexPorInmueble(int id)
        {
            var lista = repositorio.ObtenerTodos(id);
            if (TempData.ContainsKey("Id"))
                ViewBag.Id = TempData["Id"];
            if (TempData.ContainsKey("Mensaje"))
                ViewBag.Mensaje = TempData["Mensaje"];
            return View("Index", lista);
        }

        [Authorize]
        [Route("[controller]/BuscarPorFecha/{desde}/{hasta}", Name ="BuscarPorFecha")]
        public IActionResult BuscarPorFecha(DateTime desde, DateTime hasta)
        {
            try
            {
                var res = repositorio.ObtenerPorFecha(desde,hasta);
                return Json(new {Datos=res});
            }
            catch (Exception ex)
            {
                return Json(new {Error= ex.Message });
            }
        }


            // GET: ContratoController/Details/5
            [Authorize]
        public ActionResult Details(int id)
        {
            var entidad = repositorio.ObtenerPorId(id);
            return View(entidad);
        }

        // GET: ContratoController/Create
        [Authorize]
        public ActionResult Create()
        {
            ViewBag.Inquilinos = repoInquilinos.ObtenerTodos();
            ViewBag.Inmuebles = repositorioInmueble.ObtenerTodos();
            return View();
        }

        // POST: ContratoController/Create
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Contrato contrato)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    repositorio.Alta(contrato);
                    TempData["Id"] = contrato.Id;
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    ViewBag.Inquilinos = repoInquilinos.ObtenerTodos();
                    ViewBag.Inmuebles = repositorioInmueble.ObtenerTodos();
                    return View(contrato);
                }
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                ViewBag.StackTrate = ex.StackTrace;
                return View(contrato);
            }
        }

        // GET: ContratoController/Edit/5
        [Authorize]
        public ActionResult Edit(int id)
        {
            var entidad = repositorio.ObtenerPorId(id);
            ViewBag.Inquilinos = repoInquilinos.ObtenerTodos();
            ViewBag.Inmuebles = repositorioInmueble.ObtenerTodos();
            if (TempData.ContainsKey("Mensaje"))
                ViewBag.Mensaje = TempData["Mensaje"];
            if (TempData.ContainsKey("Error"))
                ViewBag.Error = TempData["Error"];
            return View(entidad);
        }

        // POST: ContratoController/Edit/5
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Contrato entidad)
        {
            try
            {
                entidad.Id = id;
                repositorio.Modificacion(entidad);
                TempData["Mensaje"] = "Datos guardados correctamente";
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.Inquilinos = repoInquilinos.ObtenerTodos();
                ViewBag.Inmuebles = repositorioInmueble.ObtenerTodos();
                ViewBag.Error = ex.Message;
                ViewBag.StackTrate = ex.StackTrace;
                return View(entidad);
            }
        }

        // GET: ContratoController/Delete/5
        [Authorize(Policy = "Administrador")]
        public ActionResult Delete(int id)
        {
            try
            {
                repositorio.Baja(id);
                TempData["Mensaje"] = "Eliminación realizada correctamente";
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                ViewBag.StackTrate = ex.StackTrace;
                return RedirectToAction(nameof(Index));
            }
        }

        // POST: ContratoController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Policy = "Administrador")]
        public ActionResult Delete(int id, Contrato entidad)
        {
            try
            {
                repositorio.Baja(id);
                TempData["Mensaje"] = "Eliminación realizada correctamente";
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                ViewBag.StackTrate = ex.StackTrace;
                return View(entidad);
            }
        }
    }
}

Controllers/PagoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using WebApplicationPrueba.Models;
using Microsoft.AspNetCore.Authorization;

namespace WebApplicationPrueba.Controllers
{
    public class PagoController : Controller
    {
        private readonly IRepositorioPago repositorio;
        private readonly IRepositorioContrato repositorioContrato;
        private readonly IConfiguration configuration;

        public PagoController(IConfiguration configuration , IRepositorioPago repositorio, IRepositorioContrato repositorioContrato)
        {
            this.repositorio = repositorio;
            this.repositorioContrato = repositorioContrato;
            this.configuration = configuration;
        }




        // GET: PagoController
        [Authorize]
        public ActionResult Index()
        {
            var lista = repositorio.ObtenerTodos();
            if (TempData.ContainsKey("Id"))
                ViewBag.Id = TempData["Id"];
            if (TempData.ContainsKey("Mensaje"))
                ViewBag.Mensaje = TempData["Mensaje"];
            return View(lista);
        }
       
        [Authorize]
        public ActionResult IndexPorContrato(int id)
        {
            var lista = repositorio.BuscarPorContrato(id);
            if (TempData.ContainsKey("Id"))
                ViewBag.Id = TempData["Id"];
            if (TempData.ContainsKey("Mensaje"))
                ViewBag.Mensaje = TempData["Mensaje"];
            ViewBag.Contrato = repositorioContrato.ObtenerPorId(id);
            return View(lista);
        }

        // GET: PagoController/Details/5
        [Authorize]
        public ActionResult Details(int id)
        {
            var entidad = repositorio.ObtenerPorId(id);
            return View(entidad);
        }

        // GET: PagoController/Create
        [Authorize]
        public ActionResult Create(int id)
        {
            
            ViewBag.Contrato = repositorioContrato.ObtenerPorId(id);

            return View();
        }

        // POST: PagoController/Create
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Pago pago)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    repositorio.Alta(pago);
                    TempData["Id"] = pago.Id;
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    ViewBag.Contrato = repositorioContrato.ObtenerTodos();
                    return View(pago);
                }
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                ViewBag.StackTrate = ex.StackTrace;
                return View(pago);
            }
        }

        // GET: PagoController/Edit/5
        [Authorize]
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: PagoController/Edit/5
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: PagoController/Delete/5
        [Authorize(Policy = "Administrador")]
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: PagoController/Delete/5
        [Authorize(Policy = "Administrador")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Views/Contrato/Create.cshtml
@model WebApplicationPrueba.Models.Contrato

@{
    ViewData["Title"] = "Crear";
}

<h1>Crear</h1>

<h4>Contrato</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <label asp-for="FechaDesde" class="control-label"></label>
                <input asp-for="FechaDesde" class="form-control" />
                <span asp-validation-for="FechaDesde" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FechaHasta" class="control-label"></label>
                <input asp-for="FechaHasta" class="form-control" />
                <span asp-validation-for="FechaHasta" class="text-danger"></span>
            </div>


            <div class="form-group">
                <label class="control-label">Inquilino</label>
                <select class="form-control" name="InquilinoId">
                    @foreach (var item in (IList<Inquilino>)ViewBag.Inquilinos)
                    {
                        <option value="@item.Id">@(item.Nombre + " " + item.Apellido)</option>
                    }
                </select>
                <span asp-validation-for="InquilinoId" class="text-danger"></span>
            </div>





            <div class="form-group">
                <label class="control-label">Inmueble</label>
                <select class="form-control" name="InmuebleId" onchange="modificarImporte()" id="inmueble">
                    @foreach (var item in (IList<Inmueble>)ViewBag.Inmuebles)
                    {
                        <option selected montoAlquiler="@item.Precio" value="@item.Id">@(item.Direccion + " Dueño :" + item.Duenio.Nombre + " " + item.Duenio.Apellido)</option>
                    }
                </select>
                <span asp-validation-for="InmuebleId" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="PrecioMensual" class="control-label"></label>
                <input asp-for="PrecioMensual" class="form-control" id="importe" />
                <span asp-validation-for="PrecioMensual" class="text-danger"></span>
            </div>


            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-outline-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Volver a la lista</a>
</div>
<script language="JavaScript" type="text/javascript">

    function modificarImporte() {
        inputInporte = document.getElementById("importe");
        valorImporte = $("#inmueble").find(':selected').attr('montoAlquiler');
        inputInporte.value = valorImporte;
    }

    window.onload = modificarImporte();

</script>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Contrato/Details.cshtml
@model WebApplicationPrueba.Models.Contrato

@{
    ViewData["Title"] = "Detalles";
}

<h1>Detalles</h1>

<div>
    <h4>Contrato Nº @Model.Id</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.FechaDesde)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.FechaDesde)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.FechaHasta)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.FechaHasta)
        </dd>
        <dt class="col-sm-2">
            Inquilino
        </dt>
        <dd class="col-sm-10">
            <a class="btn btn-outline-secondary" asp-controller="Inquilino" asp-action="Edit" asp-route-id="@Model.Inquilino.Id" title="Editar"> @(Model.Inquilino.Nombre + " "+ Model.Inquilino.Apellido)</a>

        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.InmuebleId)
        </dt>
        <dd class="col-sm-10">
            <a class="btn btn-outline-secondary" asp-controller="Inmueble" asp-action="Edit" asp-route-id="@Model.Inmueble.Id" title="Editar"> @(Model.Inmueble.Direccion + "  Inmueble Nº " + Model.Inmueble.Id)</a>

        </dd>

        <dt class="col-sm-2">
            Dueño
        </dt>
        <dd class="col-sm-10">
            <a class="btn btn-outline-secondary" asp-controller="Propietarios" asp-action="Edit" asp-route-id="@Model.Inmueble.Duenio.Id" title="Editar">  @(Model.Inmueble.Duenio.Nombre + " "+ Model.Inmueble.Duenio.Apellido)</a>

        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.PrecioMensual)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PrecioMensual)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Editar", "Edit", new {  id = Model.Id }, new { @class = "btn btn-outline-warning" }) 

    <a class="btn btn-outline-danger" asp-action="Index">Volver al a lista</a>
</div>

Views/Contrato/Edit.cshtml
@model WebApplicationPrueba.Models.Contrato

@{
    ViewData["Title"] = "Editar";
}

<h1>Editar</h1>

<h4>Contrato</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <label asp-for="FechaDesde" class="control-label"></label>
                <input asp-for="FechaDesde" class="form-control" />
                <span asp-validation-for="FechaDesde" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FechaHasta" class="control-label"></label>
                <input asp-for="FechaHasta" class="form-control" />
                <span asp-validation-for="FechaHasta" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label class="control-label">Inquilino</label>
                <select class="form-control" name="InquilinoId">
                    @foreach (var item in (IList<Inquilino>)ViewBag.Inquilinos)
                    {
                        @:<option @(item.Id == Model.InquilinoId ? "selected" : "") value="@item.Id">@(item.Nombre + " " + item.Apellido)</option>
                    }
                </select>
                <span asp-validation-for="InquilinoId" class="text-danger"></span>
            </div>




            <div class="form-group">
                <label class="control-label">Inmueble</label>
                <select class="form-control" name="InmuebleId">
                    @foreach (var item in (IList<Inmueble>)ViewBag.Inmuebles)
                    {
                        @:<option @(item.Id == Model.InmuebleId ? "selected" : "") value="@item.Id">@(item.Direccion + " Dueño :" + item.Duenio.Nombre + " " + item.Duenio.Apellido)</option>
                    }
                </select>
                <span asp-validation-for="InmuebleId" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="PrecioMensual" class="control-label"></label>
                <input asp-for="PrecioMensual" class="form-control" />
                <span asp-validation-for="PrecioMensual" class="text-danger"></span>
            </div>


            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-outline-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a class="btn btn-outline-danger" asp-action="Index">Volver a la lista</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Contrato/Index.cshtml
@model IEnumerable<WebApplicationPrueba.Models.Contrato>

@{
    ViewData["Title"] = "Contratos";
}

<h1>Contratos</h1>

<p>
    <a class="btn btn-outline-success" asp-action="Create">Crear Contrato</a>
</p>

<form id="form-buscar">
    
    <div class="row align-self-center">
        <div class="col-4">
            <div class="form-group">

                <label for="desde" class="control-label"></label>
                <input type="date" name="desde" class="form-control" placeholder="Buscar Desde" id="desde" />
                <span>
                    <label for="hasta" class="control-label"></label>
                    <input type="date" name="hasta" class="form-control" placeholder="Buscar Hasta" id="hasta" />
                </span>
                <div class="form-group mt-2 justify-content-xl-center">
                    <input type="submit" value="Buscar" class="btn btn-outline-primary" />
                </div>
            </div>
        </div>
        <div class="col-3 ">
            
        </div>
        
       
    </div>
 
</form>

<table class="table table-striped table-bordered table-hover">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FechaDesde)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FechaHasta)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.InquilinoId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.InmuebleId)
            </th>
            <th>
                Propietario
            </th>
            <th>
                Precio
            </th>

            <th></th>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody id="resultado">
        
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FechaDesde)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FechaHasta)
            </td>
            <td>
                @(item.Inquilino.Nombre + " " + item.Inquilino.Apellido)
            </td>
            <td>
                @(item.Inmueble.Direccion + "  Inmueble Nº " + item.Inmueble.Id)
            </td>
            <td>
                @(item.Inmueble.Duenio.Nombre + " " + item.Inmueble.Duenio.Apellido)

            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PrecioMensual)
            </td>
            <td>

                @Html.ActionLink("", "Edit", new { id = item.Id }, new { @class = "btn btn-outline-warning fa fa-pencil" })
            </td>
            <td>
                @Html.ActionLink("", "Details", new { id = item.Id }, new { @class = "btn btn-outline-primary fa  fa-info" })
            </td>
            <td>

                @Html.ActionLink("", "Delete", new { id = item.Id }, new { @class = "btn btn-outline-danger fa fa-trash" })
            </td>
            <td>
                <a class="btn btn-outline-secondary" asp-controller="Pago" asp-action="IndexPorContrato" asp-route-id="@item.Id" title="Pagos del contrato"><i class="fa fa-files-o"></i><i class="fa fa-eye"></i></a>
            </td>
            <td>
                <a class="btn btn-outline-secondary" asp-controller="Pago" asp-action="Create" asp-route-id="@item.Id" title="Crear Pago"><i class="fa fa-money"></i><i class="fa fa-plus"></i></a>
            </td>
        </tr>
}
    </tbody>
</table>




<!--Scripts-->
<script id="t_tabla" type="x-tmpl-mustache">
    {{#datos}}
    <tr>
        <td>{{id}}</td>
        <td>{{fechaDesde}}</td>
        <td>{{fechaHasta}}</td>


        <td>
            {{inquilino.nombre}}  {{Inquilino.apellido}}
        </td>
        <td>
            {{inmueble.direccion}} Inmueble Nº: {{inmueble.id}}
        </td>
        <td>
            {{inmueble.duenio.nombre}}  {{inmueble.duenio.apellido}}
        </td>
        <td>
            {{precioMensual}}
        </td>
        <td>
            <a href="Contrato/Edit/{{id}}" class="btn btn-outline-warning fa fa-pencil"></a>
        </td>
        <td>
            <a href="Contrato/Details/{{id}}" class="btn btn-outline-primary fa  fa-info"></a>
        </td>
        <td>
            <a href="Contrato/Delete/{{id}}" class="btn btn-outline-danger fa fa-trash"></a>
        </td>
        <td>
            <a class="btn btn-outline-secondary" href="Pago/IndexPorContrato/{{id}}" name="Pagos del contrato"><i class="fa fa-files-o"></i><i class="fa fa-eye"></a>
        </td>
        <td>
            <a class="btn btn-outline-secondary" href="Pago/Create/{{id}}" name="Crear Pago"><i class="fa fa-money"></i><i class="fa fa-plus"></i></a>
        </td>

    </tr>

    {{/datos}}
</script>

@section Scripts{ 
    <script>
        document.querySelector("#form-buscar").addEventListener("submit", (e) => {

            e.preventDefault();
            var desde = $('#desde').val();
            var hasta = $('#hasta').val();
            $.get(`@Url.Action("BuscarPorFecha", "Contrato")/${desde}/${hasta}`).done((res) => {
                console.log(res);
                var template = document.getElementById('t_tabla').innerHTML;
                var rendered = Mustache.render(template, res);
                document.getElementById('resultado').innerHTML = rendered;
            });
            return false;
        });

    </script>
}